Add domain dot seller
dappforce/polkaverse pull request #96
Opened 2023-05-05 08:50 UTC by samchuk-vlad

2023-05-18 12:02 UTC, olehmell requested changes

2023-05-18 12:34 UTC, olehmell requested changes

2023-05-18 12:34 UTC, olehmell commented on src/components/domains/EligibleDomainsSection.tsx
> +// const ClaimFreeDomainSection = ({ domain: { id: domain } }: DomainProps) => {
Extract it to some another file

2023-05-18 12:34 UTC, olehmell commented on src/components/domains/EligibleDomainsSection.tsx
> +  if (account && signer && account !== myAddress && signer !== myAddress) {
Dirty :(

Maybe we can skip account && signer?

because if it undefined it is `false` here: account !== myAddress && signer !== myAddress

2023-05-31 12:51 UTC, samchuk-vlad commented on src/components/domains/dot-seller/utils.tsx
> +    dispatch(fetchPendingOrdersByAccount({ id: account, reload: true }))
accout - current user address
signer - address that sign tx

2023-05-31 12:56 UTC, samchuk-vlad commented on src/config/env.ts
> +export const nodeEnv = process.env['NEXT_PUBLIC_NODE_ENV']
it didn't work that way

2023-05-31 12:58 UTC, samchuk-vlad commented on src/rtk/features/domainPendingOrders/pendingOrdersHooks.ts
> +// TODO: check this case
Old comment)

2023-10-05 09:55 UTC, merged